services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - task-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8085:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - task-network

  eureka-server:
    build:
      context: "./Eureka Server/Eureka-Server"
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - task-network

  auth-service:
    build:
      context: "./Auth_services"
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/auth_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - task-network

  task-service:
    build:
      context: "./task-service"
      dockerfile: Dockerfile
    container_name: task-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task_management_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - task-network

  project-service:
    build:
      context: "./project_service"
      dockerfile: Dockerfile
    container_name: project-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task_management?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - task-network

  profile-service:
    build:
      context: "./Profile_service/Profile_service"
      dockerfile: Dockerfile
    container_name: profile-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/profile_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - task-network

  api-gateway:
    build:
      context: "./API_Category"
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
      - auth-service
      - task-service
      - project-service
      - profile-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - task-network

  frontend:
    build:
      context: "./frontTask"
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
    restart: unless-stopped
    networks:
      - task-network

volumes:
  mysql_data:

networks:
  task-network:
    driver: bridge