spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://auth-service:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=task-service
spring.cloud.gateway.routes[1].uri=http://task-service:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/tasks/**,/api/notifications/**

spring.cloud.gateway.routes[2].id=project-service
spring.cloud.gateway.routes[2].uri=http://project-service:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/projects/**

spring.cloud.gateway.routes[3].id=profile-service
spring.cloud.gateway.routes[3].uri=http://profile-service:8083
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/profiles/**

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
